name: static-check-ts

on:
  push:
    paths:
      - website
  workflow_dispatch:

jobs:
  build:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/static-check-ts
